export { TransportRegistry } from './registry'
export { BaileysAdapter } from './adapters/baileys-adapter'
export { GupshupAdapter } from './adapters/gupshup-adapter'
export { SimulationAdapter } from './adapters/simulation-adapter'
export type { TransportAdapter, OutboundMessage, SendResult, ChannelHealth, ConnectionState } from './types'
