import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface StatementInvoice {
  invoiceNumber: string
  date: string
  total: number
  payLink?: string
}

export interface StatementData {
  merchantName: string
  customerName: string
  invoices: StatementInvoice[]
  totalOutstanding: number
  date: string
}

export function generateStatementPdf(data: StatementData): Buffer {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const contentWidth = pageWidth - margin * 2

  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(data.merchantName || 'Outstanding Statement', pageWidth / 2, 30, { align: 'center' })

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Outstanding Statement', pageWidth / 2, 40, { align: 'center' })

  // Date
  doc.setFontSize(9)
  doc.text(`Date: ${data.date}`, margin, 55)
  doc.text(`Customer: ${data.customerName}`, margin, 62)

  // Line
  doc.setDrawColor(200)
  doc.line(margin, 68, pageWidth - margin, 68)

  // Invoice table
  const hasPayLinks = data.invoices.some(inv => inv.payLink)
  const tableHeaders = hasPayLinks
    ? [['#', 'Invoice', 'Date', 'Amount', 'Pay Link']]
    : [['#', 'Invoice', 'Date', 'Amount']]
  const tableRows = data.invoices.map((inv, i) => {
    const row = [
      String(i + 1),
      inv.invoiceNumber,
      inv.date,
      `₹ ${inv.total.toLocaleString('en-IN')}`,
    ]
    if (hasPayLinks) {
      row.push(inv.payLink ? inv.payLink.replace(/^https?:\/\//, '') : '')
    }
    return row
  })

  autoTable(doc, {
    head: tableHeaders,
    body: tableRows,
    startY: 74,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [50, 50, 50],
      textColor: 255,
      fontStyle: 'bold',
    },
    columnStyles: hasPayLinks
      ? {
          0: { cellWidth: 10, halign: 'center' },
          1: { cellWidth: 40 },
          2: { cellWidth: 35 },
          3: { cellWidth: 35, halign: 'right' },
          4: { cellWidth: 55 },
        }
      : {
          0: { cellWidth: 10, halign: 'center' },
          1: { cellWidth: 55 },
          2: { cellWidth: 45 },
          3: { cellWidth: 45, halign: 'right' },
        },
    foot: [[
      { content: '', colSpan: hasPayLinks ? 4 : 3, styles: { fontStyle: 'bold' } },
      { content: `₹ ${data.totalOutstanding.toLocaleString('en-IN')}`, styles: { fontStyle: 'bold', halign: 'right', fontSize: 10 } },
    ]],
    footStyles: {
      fillColor: [240, 240, 240],
    },
  })

  const footerY = (doc as any).lastAutoTable.finalY + 15

  // Footer
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Please contact us for payment details.', margin, footerY)
  doc.setFontSize(8)
  doc.text(`Generated by BillZo — ${data.date}`, margin, footerY + 7)

  return Buffer.from(doc.output('arraybuffer'))
}
