import type { PipelineContract, PipelineId } from './pipelines'

export const PipelineRegistry: Record<PipelineId, PipelineContract> = {
  'invoice.created': {
    id: 'invoice.created',
    producer: 'POS',
    consumers: ['sync', 'worker', 'recovery'],
    expectedSideEffects: [
      'invoices table updated',
      'sync queued',
      'outbox event invoice.created emitted',
      'recovery case created if unpaid',
      'dashboard count updated',
    ],
    idempotent: false,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 2000,
    critical: true,
  },

  'invoice.updated': {
    id: 'invoice.updated',
    producer: 'POS',
    consumers: ['sync', 'worker', 'recovery'],
    expectedSideEffects: [
      'invoices table updated',
      'sync queued',
      'outbox event invoice.updated emitted',
      'recovery case recalculated',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 2000,
    critical: true,
  },

  'payment.completed': {
    id: 'payment.completed',
    producer: 'PaymentSheet',
    consumers: ['sync', 'worker.outbox', 'worker.recovery'],
    expectedSideEffects: [
      'payments table updated',
      'invoice paid_amount updated',
      'outbox event payment.completed emitted',
      'worker processes recovery projection',
      'recovery case state updated',
      'dashboard cash metrics updated',
    ],
    idempotent: true,
    retryable: true,
    compensable: true,
    expectedLatencyMs: 3000,
    critical: true,
  },

  'payment.failed': {
    id: 'payment.failed',
    producer: 'PaymentSheet',
    consumers: ['sync', 'worker.outbox'],
    expectedSideEffects: [
      'payments table updated with failed status',
      'outbox event payment.failed emitted',
      'no recovery state change',
    ],
    idempotent: true,
    retryable: false,
    compensable: false,
    expectedLatencyMs: 500,
    critical: false,
  },

  'reminder.requested': {
    id: 'reminder.requested',
    producer: 'decision-engine',
    consumers: ['worker.reminders', 'scheduler'],
    expectedSideEffects: [
      'reminder event queued in reminders queue',
      'next reminder scheduled with escalation stage',
      'outbox event reminder.requested emitted',
    ],
    idempotent: false,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 1000,
    critical: true,
  },

  'reminder.sent': {
    id: 'reminder.sent',
    producer: 'worker.reminders',
    consumers: ['timeline', 'recovery', 'behavioral'],
    expectedSideEffects: [
      'whatsapp_event created',
      'invoice lastReminderAt updated',
      'reminder count incremented',
      'recovery case engagement updated',
      'timeline event created',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 5000,
    critical: true,
  },

  'promise.created': {
    id: 'promise.created',
    producer: 'QueueActions',
    consumers: ['worker', 'recovery'],
    expectedSideEffects: [
      'promises table updated',
      'recovery case nextActionType set to wait',
      'outbox event promise.created emitted',
      'automation mode may update',
    ],
    idempotent: false,
    retryable: true,
    compensable: true,
    expectedLatencyMs: 1000,
    critical: true,
  },

  'promise.broken': {
    id: 'promise.broken',
    producer: 'scheduler',
    consumers: ['worker', 'recovery', 'decision-engine'],
    expectedSideEffects: [
      'promise status set to broken',
      'brokenPromises counter incremented',
      'recovery case escalated to critical',
      'nextActionType set to call',
      'outbox event promise.broken emitted',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 2000,
    critical: true,
  },

  'promise.fulfilled': {
    id: 'promise.fulfilled',
    producer: 'system',
    consumers: ['recovery'],
    expectedSideEffects: [
      'promise status set to fulfilled',
      'recovery case state may improve',
    ],
    idempotent: true,
    retryable: false,
    compensable: false,
    expectedLatencyMs: 500,
    critical: false,
  },

  'recovery.case.created': {
    id: 'recovery.case.created',
    producer: 'system',
    consumers: ['worker', 'decision-engine'],
    expectedSideEffects: [
      'recovery_cases table updated',
      'decision engine runs for initial action',
      'reminder scheduled if applicable',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 1000,
    critical: true,
  },

  'recovery.case.updated': {
    id: 'recovery.case.updated',
    producer: 'worker',
    consumers: ['decision-engine', 'dashboard'],
    expectedSideEffects: [
      'recovery_cases state updated',
      'dashboard pending actions recalculated',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 1000,
    critical: true,
  },

  'recovery.case.closed': {
    id: 'recovery.case.closed',
    producer: 'worker',
    consumers: ['dashboard'],
    expectedSideEffects: [
      'recovery case status set to recovered',
      'no further reminders scheduled',
      'attribution recorded',
      'dashboard updated',
    ],
    idempotent: true,
    retryable: false,
    compensable: false,
    expectedLatencyMs: 500,
    critical: false,
  },

  'customer.created': {
    id: 'customer.created',
    producer: 'POS',
    consumers: ['sync', 'dashboard'],
    expectedSideEffects: [
      'customers table updated',
      'sync queued',
      'dashboard customer count updated',
    ],
    idempotent: false,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 1000,
    critical: false,
  },

  'customer.updated': {
    id: 'customer.updated',
    producer: 'POS',
    consumers: ['sync', 'dashboard'],
    expectedSideEffects: [
      'customers table updated',
      'sync queued',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 500,
    critical: false,
  },

  'sync.queued': {
    id: 'sync.queued',
    producer: 'POS',
    consumers: ['sync-engine'],
    expectedSideEffects: [
      'queue item created',
      'background sync scheduled',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 100,
    critical: true,
  },

  'sync.completed': {
    id: 'sync.completed',
    producer: 'sync-engine',
    consumers: ['dashboard', 'dexie'],
    expectedSideEffects: [
      'sync status set to synced',
      'dexie data refreshed',
      'dashboard reload triggered',
    ],
    idempotent: true,
    retryable: false,
    compensable: false,
    expectedLatencyMs: 10000,
    critical: true,
  },

  'sync.failed': {
    id: 'sync.failed',
    producer: 'sync-engine',
    consumers: ['retry-queue'],
    expectedSideEffects: [
      'sync status set to failed',
      'retry scheduled with backoff',
      'dead letter after max retries',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 500,
    critical: true,
  },

  'outbox.event.created': {
    id: 'outbox.event.created',
    producer: 'domain',
    consumers: ['worker.outbox'],
    expectedSideEffects: [
      'outbox table event inserted',
      'worker will pick up on next poll',
    ],
    idempotent: false,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 100,
    critical: true,
  },

  'outbox.event.processed': {
    id: 'outbox.event.processed',
    producer: 'worker.outbox',
    consumers: ['recovery', 'behavioral', 'attribution', 'notification'],
    expectedSideEffects: [
      'outbox status set to processed',
      'business projection updated',
      'dashboard notified of change',
    ],
    idempotent: true,
    retryable: false,
    compensable: false,
    expectedLatencyMs: 2000,
    critical: true,
  },

  'outbox.event.dead_letter': {
    id: 'outbox.event.dead_letter',
    producer: 'worker.outbox',
    consumers: ['retry-queue'],
    expectedSideEffects: [
      'outbox status set to dead_letter',
      'retry queue scheduled',
      'notification sent after 3 failures',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 60000,
    critical: true,
  },

  'dashboard.refreshed': {
    id: 'dashboard.refreshed',
    producer: 'work-store',
    consumers: ['dashboard-ui'],
    expectedSideEffects: [
      'work-store.getDashboard() called',
      'sections array returned',
      'UI re-renders with latest data',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 5000,
    critical: false,
  },

  'decision.engine.ran': {
    id: 'decision.engine.ran',
    producer: 'worker',
    consumers: ['recovery', 'scheduler'],
    expectedSideEffects: [
      'decision engine evaluates recovery case',
      'next action determined',
      'reminder scheduled if applicable',
    ],
    idempotent: true,
    retryable: true,
    compensable: false,
    expectedLatencyMs: 500,
    critical: true,
  },

  'scheduler.tick': {
    id: 'scheduler.tick',
    producer: 'system',
    consumers: ['worker.reminders', 'worker.recovery'],
    expectedSideEffects: [
      'due reminders fired',
      'promises evaluated for broken status',
      'overdue escalation checked',
    ],
    idempotent: true,
    retryable: false,
    compensable: false,
    expectedLatencyMs: 10000,
    critical: true,
  },

  'projection.delta.emitted': {
    id: 'projection.delta.emitted',
    producer: 'worker',
    consumers: ['dashboard', 'websocket'],
    expectedSideEffects: [
      'projection delta stored',
      'dashboard notified of change',
    ],
    idempotent: true,
    retryable: false,
    compensable: false,
    expectedLatencyMs: 500,
    critical: false,
  },
} as const
